# Generated by Django 5.2.14 on 2026-05-10 10:31

import apps.cms.models.menu
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_employee_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address_floor', models.TextField(blank=True, default='')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('contact_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('operating_hours_start', models.TimeField(blank=True, null=True)),
                ('operating_hours_end', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canteen_locations', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canteen_locations', to='accounts.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canteen_locations', to='accounts.location')),
            ],
            options={
                'db_table': 'cms_canteen_locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GuestOrder',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, db_column='order_number', max_length=50, null=True, unique=True)),
                ('guest_name', models.CharField(db_column='guest_name', max_length=200)),
                ('guest_email', models.CharField(blank=True, db_column='guest_email', default='', max_length=254)),
                ('phone', models.CharField(db_column='guest_mobile', max_length=20)),
                ('total', models.DecimalField(db_column='total_amount', decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('prepared', 'Prepared'), ('collected', 'Collected'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_column='status', default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('estimated_time', models.TimeField(blank=True, db_column='estimated_time', null=True)),
                ('special_instructions', models.TextField(blank=True, db_column='special_instructions')),
                ('canteen', models.ForeignKey(blank=True, db_column='canteen_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_orders', to='cms.canteenlocation')),
            ],
            options={
                'db_table': 'cms_guest_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestOrderItem',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='item_name', max_length=200)),
                ('price', models.DecimalField(db_column='unit_price', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('qty', models.PositiveIntegerField(db_column='quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_custom', models.BooleanField(db_column='is_custom', default=False)),
                ('description', models.TextField(blank=True, db_column='item_description', default='')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.guestorder')),
            ],
            options={
                'db_table': 'cms_guest_order_items',
            },
        ),
        migrations.CreateModel(
            name='KitchenCounterUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(db_index=True)),
                ('canteen_id', models.UUIDField(db_index=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('KITCHEN', 'Kitchen'), ('COUNTER', 'Counter')], db_index=True, max_length=10)),
                ('pin_hash', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kitchen / Counter User',
                'verbose_name_plural': 'Kitchen / Counter Users',
                'db_table': 'cms_kitchen_counter_users',
                'indexes': [models.Index(fields=['username', 'is_active'], name='idx_kcu_username_active'), models.Index(fields=['canteen_id', 'role'], name='idx_kcu_canteen_role')],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='cms.canteenlocation')),
            ],
            options={
                'db_table': 'cms_menu_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, help_text='Stored in MEDIA_ROOT/item-image/ with the item name in the file path.', null=True, upload_to=apps.cms.models.menu.menu_item_photo_upload_to)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Default price. Overridden by cms_pricing_rules in Phase 2.', max_digits=10)),
                ('unit', models.CharField(default='plate', max_length=30)),
                ('is_veg', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('MEAL', 'Meal')], default='MEAL', max_length=20)),
                ('display_tag', models.CharField(blank=True, default='', max_length=50)),
                ('max_qty_per_order', models.PositiveIntegerField(default=3)),
                ('max_qty_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='cms.canteenlocation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cms.menucategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_menu_items', to='accounts.employee')),
            ],
            options={
                'db_table': 'cms_menu_items',
                'ordering': ['canteen_id', 'name'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['canteen_id', 'is_active'], name='idx_mcat_canteen_active'),
        ),
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('canteen', 'name')},
        ),
        migrations.AddIndex(
            model_name='menuorderitem',
            index=models.Index(fields=['canteen_id', 'deleted_at', 'name'], name='idx_mi_canteen_del_name'),
        ),
        migrations.AddIndex(
            model_name='menuorderitem',
            index=models.Index(fields=['canteen_id', 'deleted_at', 'category_id'], name='idx_mi_canteen_del_cat'),
        ),
        migrations.AddIndex(
            model_name='menuorderitem',
            index=models.Index(fields=['canteen_id', 'deleted_at', 'item_type'], name='idx_mi_canteen_del_type'),
        ),
        migrations.AddIndex(
            model_name='menuorderitem',
            index=models.Index(fields=['canteen_id', 'deleted_at', 'is_available'], name='idx_mi_canteen_del_avail'),
        ),
        migrations.AddIndex(
            model_name='menuorderitem',
            index=models.Index(fields=['id', 'canteen_id', 'deleted_at'], name='idx_mi_id_canteen_del'),
        ),
        migrations.AddConstraint(
            model_name='menuorderitem',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('canteen'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_active_menu_item_name_per_canteen_ci'),
        ),
    ]
