# Generated by Django 5.2.14 on 2026-05-10 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_fields'),
        ('cms', '0002_menuitemslotconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slot_id', models.CharField(db_index=True, max_length=100)),
                ('slot_name', models.CharField(max_length=100)),
                ('slot_start', models.TimeField(blank=True, null=True)),
                ('slot_end', models.TimeField(blank=True, null=True)),
                ('order_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('PREPARED', 'Prepared'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('payment_mode', models.CharField(choices=[('WALLET', 'Wallet'), ('SALARY', 'Salary'), ('CASH', 'Cash')], default='WALLET', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('billing_period', models.CharField(blank=True, default='', max_length=7)),
                ('is_billed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cms.canteenlocation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canteen_orders', to='accounts.employee')),
            ],
            options={
                'db_table': 'cms_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CmsOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name_snapshot', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_price_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pricing_rule', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_items', to='cms.menuorderitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cms.cmsorder')),
            ],
            options={
                'db_table': 'cms_order_items',
            },
        ),
        migrations.CreateModel(
            name='EmployeeWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('last_recharged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_wallets', to='accounts.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_wallet', to='accounts.employee')),
            ],
            options={
                'db_table': 'cms_employee_wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='accounts.employee')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='cms.cmsorder')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cms.employeewallet')),
            ],
            options={
                'db_table': 'cms_wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cmsorder',
            index=models.Index(fields=['canteen_id', 'order_date', 'status'], name='idx_order_canteen_date_status'),
        ),
        migrations.AddIndex(
            model_name='cmsorder',
            index=models.Index(fields=['employee_id', 'order_date'], name='idx_order_employee_date'),
        ),
        migrations.AddIndex(
            model_name='cmsorder',
            index=models.Index(fields=['slot_id', 'order_date', 'status'], name='idx_order_slot_date_status'),
        ),
        migrations.AddIndex(
            model_name='employeewallet',
            index=models.Index(fields=['company_id', 'is_active'], name='idx_wallet_company_active'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['employee_id', 'created_at'], name='idx_wallet_tx_employee_created'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='idx_wallet_tx_type_created'),
        ),
    ]
