# Generated by Django 5.2.14 on 2026-05-10 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_cmsorder_cmsorderitem_employeewallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slot_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('MEAL', 'Meal'), ('SNACK', 'Snack')], default='MEAL', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ordering_opens_at', models.TimeField(blank=True, null=True)),
                ('ordering_deadline_time', models.TimeField()),
                ('cancellation_deadline_time', models.TimeField()),
                ('max_orders', models.PositiveIntegerField(blank=True, null=True)),
                ('applicable_days', models.JSONField(blank=True, default=list)),
                ('display_color', models.CharField(default='#3b82f6', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='cms.canteenlocation')),
            ],
            options={
                'db_table': 'cms_time_slots',
                'ordering': ['start_time', 'name'],
                'indexes': [models.Index(fields=['canteen_id', 'is_active'], name='idx_timeslot_canteen_active')],
                'constraints': [models.UniqueConstraint(fields=('canteen', 'name'), name='uniq_time_slot_name_per_canteen')],
            },
        ),
    ]
